Animations + sticky scroll
Hack-Weekly/onyx-sal-blog pull request #40
Opened 2023-04-04 01:54 UTC by julianp15

2023-04-04 01:56 UTC, julianp15 commented on client/src/Layout.jsx
> -import { Footer } from "./components/Footer";
THis should not be removed sorry

2023-04-04 02:33 UTC, jpatterson933 commented on client/src/Layout.jsx
> -import { Footer } from "./components/Footer";
@julianp15 You can fix it and repush the branch and it will update here

2023-04-04 02:36 UTC, jpatterson933 commented on client/src/Layout.jsx
> -      <Footer />
This is the same footer component that should still be there.

2023-04-04 02:37 UTC, jpatterson933 commented on client/src/Layout.jsx
> +      <footer id="#footer-bar">
`<Footer />` would go here

2023-04-04 02:37 UTC, jpatterson933 reviewed
Everything looks good except for the Footer component. that just needs to be fixed and added back into its original place.

2023-04-04 16:47 UTC, StephenODea54 requested changes

2023-04-04 16:47 UTC, StephenODea54 commented on client/src/Layout.jsx
> +      <footer id="#footer-bar">
This element needs removed, otherwise all good!

2023-04-04 17:36 UTC, StephenODea54 approved these changes
Awesome, looks good!

2023-04-04 17:40 UTC, jpatterson933 approved these changes
Good fix!

2023-04-04 17:43 UTC, merged

2023-04-06 14:33 UTC, nathanjslim commented
@julianp15 Clicking the title screen does not return us to home page. Not sure if you attempted to address this in Layout.jsx or not; could you revisit and add this?

If you're too busy I can fix this as well. Let me know